/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT flight_project.cdb */

/* MODULE PARAMETERS */
GBL_USERINITFXN = _FXN_F_nop;

MEM_SEGZERO = SDRAM;
MEM_MALLOCSEG = SDRAM;

CLK_TIMEFXN = CLK_F_getshtime;
CLK_HOOKFXN = HWI_F_dispatch;

PRD_THOOKFXN = _KNL_tick;

RTDX_DATAMEMSEG = IDRAM;

HST_DSMBUFSEG = IDRAM;

SWI_EHOOKFXN = GBL_NULL;
SWI_IHOOKFXN = GBL_NULL;
SWI_EXECFXN = SWI_F_iexec;
SWI_RUNFXN = SWI_F_run;

TSK_STACKSEG = MEM_NULL;
TSK_VCREATEFXN = _FXN_F_nop;
TSK_VDELETEFXN = _FXN_F_nop;
TSK_VEXITFXN = _FXN_F_nop;

IDL_CALIBRFXN = GBL_NULL;

SYS_ABORTFXN = _UTL_doAbort;
SYS_ERRORFXN = _UTL_doError;
SYS_EXITFXN = _UTL_halt;
SYS_PUTCFXN = _UTL_doPutc;

GIO_CREATEFXN = _FXN_F_nop;
GIO_DELETEFXN = _FXN_F_nop;
GIO_PENDFXN = _FXN_F_nop;
GIO_POSTFXN = _FXN_F_nop;

/* OBJECT ALIASES */
_IPRAM = IPRAM;
_IDRAM = IDRAM;
_SBSRAM = SBSRAM;
_SDRAM = SDRAM;
_VECS = VECS;
_Propulsion = Propulsion;
_Comm_TDMA_Mgr = Comm_TDMA_Mgr;
_Control_Dispatch = Control_Dispatch;
_FastHousekeeping = FastHousekeeping;
_Telemetry = Telemetry;
_HWI_RESET = HWI_RESET;
_HWI_NMI = HWI_NMI;
_HWI_RESERVED0 = HWI_RESERVED0;
_HWI_RESERVED1 = HWI_RESERVED1;
_HWI_INT4 = HWI_INT4;
_HWI_INT5 = HWI_INT5;
_HWI_INT6 = HWI_INT6;
_HWI_INT7 = HWI_INT7;
_HWI_INT8 = HWI_INT8;
_HWI_INT9 = HWI_INT9;
_HWI_INT10 = HWI_INT10;
_HWI_INT11 = HWI_INT11;
_HWI_INT12 = HWI_INT12;
_HWI_INT13 = HWI_INT13;
_HWI_INT14 = HWI_INT14;
_HWI_INT15 = HWI_INT15;
_PRD_swi = PRD_swi;
_KNL_swi = KNL_swi;
_packet_TX_swi = packet_TX_swi;
_PADS = PADS;
_Controller = Controller;
_TSK_idle = TSK_idle;
_TSK_comm_mgr = TSK_comm_mgr;
_TSK_gsp_task = TSK_gsp_task;
_TSK_datacomm_STL = TSK_datacomm_STL;
_TSK_bkg_flash_write = TSK_bkg_flash_write;
_TSK_cp_monitor = TSK_cp_monitor;
_TSK_datacomm_STS = TSK_datacomm_STS;
_TSK_estimator = TSK_estimator;
_LOG_system = LOG_system;
_trace = trace;
_PIP_comm_TX = PIP_comm_TX;
_PIP_comm_RX = PIP_comm_RX;
_SEM_Comm_TX_enable_STS = SEM_Comm_TX_enable_STS;
_SEM_Comm_Activity = SEM_Comm_Activity;
_SEM_Comm_TX_enable_STL = SEM_Comm_TX_enable_STL;
_SEM_gsp_task = SEM_gsp_task;
_SEM_global_pads_request = SEM_global_pads_request;
_SEM_datacomm_STL = SEM_datacomm_STL;
_SEM_update_flash = SEM_update_flash;
_SEM_datacomm_STS = SEM_datacomm_STS;
_MBX_CommSTL_LO = MBX_CommSTL_LO;
_MBX_CommSTL_HI = MBX_CommSTL_HI;
_MBX_CommSTS_HI = MBX_CommSTS_HI;
_MBX_CommSTS_LO = MBX_CommSTS_LO;
_MBX_Task_Triggers = MBX_Task_Triggers;
_MBX_Estimator = MBX_Estimator;
_MBX_CommEXPv2 = MBX_CommEXPv2;

/* MODULE GBL */

SECTIONS {
   .vers (COPY): {} /* version information */
}

-priority
-llnknone.a62
-ldrivers.a67          /* device drivers support */
-lsioboth.a62          /* supports both SIO models */
-lbios.a62             /* DSP/BIOS support */
-lrtdx.lib             /* RTDX support */
-lcsl6701.lib
-lrts6700.lib          /* C and C++ run-time library support */

_GBL_CACHE = GBL_CACHE;

/* MODULE MEM */
-stack 0x8000
MEMORY {
   IPRAM       : origin = 0x400,       len = 0xfc00
   IDRAM       : origin = 0x80000000,  len = 0x10000
   SBSRAM      : origin = 0x400000,    len = 0x80000
   SDRAM       : origin = 0x2048000,   len = 0xfb8000
   VECS        : origin = 0x0,         len = 0x400
}
/* MODULE CLK */
SECTIONS {
   .clk: {
        _CLK_start = _CLK_start6x;
        CLK_F_gethtime = CLK_F_getshtime;
        CLK_A_TABBEG = .;
        *(.clk)
        CLK_A_TABEND = .;
        CLK_A_TABLEN = (. - CLK_A_TABBEG) / 1;
   } > IDRAM 
}
_CLK_PRD = CLK_PRD;
_CLK_COUNTSPMS = CLK_COUNTSPMS;
_CLK_REGS = CLK_REGS;
_CLK_USETIMER = CLK_USETIMER;
_CLK_TIMERNUM = CLK_TIMERNUM;
_CLK_TDDR = CLK_TDDR;

/* MODULE PRD */
SECTIONS {
   .prd: {
        PRD_A_TABBEG = .;
        *(.prd)
        PRD_A_TABEND = .;
        PRD_A_TABLEN = (. - PRD_A_TABBEG) / 32;
   } > IDRAM
}

/* MODULE HWI */
SECTIONS {
    .hwi_vec: 0x0 {
        HWI_A_VECS = .;
        *(.hwi_vec)
    }
}

/* MODULE SWI */
SECTIONS {
   .swi: {
        SWI_A_TABBEG = .;
        *(.swi)
        SWI_A_TABEND = .;
        SWI_A_TABLEN = (. - SWI_A_TABBEG) / 44;
   } > IDRAM
}

/* MODULE IDL */
SECTIONS {
   .idl: {
        IDL_A_TABBEG = .;
        *(.idl)
        IDL_A_TABEND = .;
        IDL_A_TABLEN = (. - IDL_A_TABBEG) / 8;
        IDL_A_CALBEG = .;
        *(.idlcal)
        IDL_A_CALEND = .;
        IDL_A_CALLEN = (. - IDL_A_CALBEG) / 8;
   } > IDRAM
}



SECTIONS {
        .sysdata: {} > IDRAM
        
        .args: fill=0 {
            *(.args)
            . += 0x4;
        } > IDRAM
        
        .trcdata:    {} > IDRAM
        
        .trace: fill = 0x0 {
           _SYS_PUTCBEG = .;
           . += 0x200;
           _SYS_PUTCEND = . - 1;
        } > IDRAM
        
        .mem: 	  {} > IDRAM
        
        .sys:     {} > IDRAM
        
        .sysregs: {} > IDRAM
        
        .sts: {
             STS_A_TABBEG = .;
            _STS_A_TABBEG = .;
            /* no STS objects */
            STS_A_TABEND = .;
            _STS_A_TABEND = .;
             STS_A_TABLEN = (. - _STS_A_TABBEG) / 16;
            _STS_A_TABLEN = (. - _STS_A_TABBEG) / 16;
        } > IDRAM
        
        .MBX_CommEXPv2$que: align = 0x4 {
            MBX_CommEXPv2$queElems = .;
            . += 20960;
        } > IDRAM
        
        .MBX_CommSTS_HI$que: align = 0x4 {
            MBX_CommSTS_HI$queElems = .;
            . += 3120;
        } > IDRAM
        
        .MBX_CommSTL_HI$que: align = 0x4 {
            MBX_CommSTL_HI$queElems = .;
            . += 3120;
        } > IDRAM
        
        .mbx: {} > IDRAM
        
        .sem: {} > IDRAM
        
        .switch:    {} > IDRAM
        
        /* PIP_comm_TX buffer */
        .pip0: {} > IDRAM
        
        .pip: {
             PIP_A_TABBEG = .;
            _PIP_A_TABBEG = .;
            *(.pip)
            PIP_A_TABEND = .;
            _PIP_A_TABEND = .;
             PIP_A_TABLEN = (. - _PIP_A_TABBEG) / 100;
            _PIP_A_TABLEN = (. - _PIP_A_TABBEG) / 100;
        } > IDRAM
        
        /* trace buffer */
        .trace$buf: align = 0x400 fill = 0xffffffff {} > IDRAM
        
        /* LOG_system buffer */
        .LOG_system$buf: align = 0x100 fill = 0xffffffff {} > IDRAM
        
        .printf (COPY): {} > IDRAM
        
        .log: {
             LOG_A_TABBEG = .;
            _LOG_A_TABBEG = .;
            *(.log)
            LOG_A_TABEND = .;
            _LOG_A_TABEND = .;
             LOG_A_TABLEN = (. - _LOG_A_TABBEG) / 24;
            _LOG_A_TABLEN = (. - _LOG_A_TABBEG) / 24;
        } > IDRAM
        
        .hst: {
             HST_A_TABBEG = .;
            _HST_A_TABBEG = .;
            /* no HST objects */
            HST_A_TABEND = .;
            _HST_A_TABEND = .;
             HST_A_TABLEN = (. - _HST_A_TABBEG) / 20;
            _HST_A_TABLEN = (. - _HST_A_TABBEG) / 20;
        } > IDRAM
        
        .dsm: {} > IDRAM
        
        .TSK_datacomm_STS$stk: {
            *(.TSK_datacomm_STS$stk)
        } > IDRAM
        
        .tsk: {
            *(.tsk)
        } > IDRAM
        
        .TSK_idle$stk: {
            *(.TSK_idle$stk)
        } > IDRAM
        
        .TSK_cp_monitor$stk: {
            *(.TSK_cp_monitor$stk)
        } > IDRAM
        
        .gio:     {} > IDRAM
        
        .TSK_datacomm_STL$stk: {
            *(.TSK_datacomm_STL$stk)
        } > IDRAM
        
        .hwi: {}  > IPRAM
        
        .bios:    {} > IPRAM
        
        .stack: fill=0xc0ffee {
            GBL_stackbeg = .;
            *(.stack)
            GBL_stackend = GBL_stackbeg + 0x8000 - 1;
            _HWI_STKBOTTOM = GBL_stackbeg + 0x8000 - 4 & ~7;
            _HWI_STKTOP = GBL_stackbeg;
        } > SBSRAM
        
        .bss:     {} > SDRAM
        
        .far:     {} > SDRAM
        
        .gblinit:    {} > SDRAM
        
        .TSK_estimator$stk: {
            *(.TSK_estimator$stk)
        } > SDRAM
        
        frt:    {} > SDRAM
        
        .text:    {} > SDRAM
        
        .cio:     {} > SDRAM
        
        .TSK_comm_mgr$stk: {
            *(.TSK_comm_mgr$stk)
        } > SDRAM
        
        .const:    {} > SDRAM
        
        .data:    {} > SDRAM
        
        .MBX_CommSTL_LO$que: align = 0x4 {
            MBX_CommSTL_LO$queElems = .;
            . += 3120;
        } > SDRAM
        
        .pinit:   {} > SDRAM
        
        .cinit:    {} > SDRAM
        
        .MBX_CommSTS_LO$que: align = 0x4 {
            MBX_CommSTS_LO$queElems = .;
            . += 3120;
        } > SDRAM
        
        .MBX_Task_Triggers$que: align = 0x4 {
            MBX_Task_Triggers$queElems = .;
            . += 640;
        } > SDRAM
        
        .MBX_Estimator$que: align = 0x4 {
            MBX_Estimator$queElems = .;
            . += 22000;
        } > SDRAM
        
        /* PIP_comm_RX buffer */
        .pip1: {} > SDRAM
        
        .TSK_bkg_flash_write$stk: {
            *(.TSK_bkg_flash_write$stk)
        } > SDRAM
        
        .sysinit:    {} > SDRAM
        
        .TSK_gsp_task$stk: {
            *(.TSK_gsp_task$stk)
        } > SDRAM
        
        .SDRAM$heap: {
            SDRAM$B = .;
            _SDRAM_base = .;
            SDRAM$L = 0x600000;
            _SDRAM_length = 0x600000;
            . += 0x600000;
        } > SDRAM
        
}

